(function ensightenInit(){var ensightenOptions = {client: "dell", clientId: 123, publishPath: "marketing", isPublic:0, serverComponentLocation: "nexus.ensighten.com/dell/marketing/serverComponent.php", staticJavascriptPath: "nexus.ensighten.com/dell/marketing/code/", ns: 'Marketing', nexus:"nexus.ensighten.com", scUseCacheBuster: "true", enableTagAuditBeacon : "false", enablePagePerfBeacon : "false", registryNs : "ensBootstraps", generatedOn : "Thu Dec 15 15:49:55 GMT 2022", beaconSamplingSeedValue: 11};
if ( !window[ensightenOptions.ns] ) {
window[ensightenOptions.registryNs]||(window[ensightenOptions.registryNs]={});
window[ensightenOptions.registryNs][ensightenOptions.ns]=window[ensightenOptions.ns]=function(l){function m(a){this.name="DependencyNotAvailableException";this.message="Dependency with id "+a+"is missing"}function n(a){this.name="BeaconException";this.message="There was an error durring beacon initialization";a=a||{};this.lineNumber=a.lineNumber||a.line;this.fileName=a.fileName}function q(){for(var a=c.dataDefinitionIds.length,b=!0,d=0;d<a;d++){var f=c.dataDefinitions[c.dataDefinitionIds[d]];if(!f||
null==f.endRegistration){b=!1;break}}b&&c.callOnDataDefintionComplete()}var e={},c={};c.ensightenOptions=ensightenOptions;c.scDataObj={};e.version="1.26.0";e.nexus=l.nexus||"nexus.ensighten.com";e.rand=-1;e.currSec=(new Date).getSeconds();e.options={interval:l.interval||100,erLoc:l.errorLocation||e.nexus+"/error/e.gif",scLoc:l.serverComponentLocation||e.nexus+"/"+l.client+"/serverComponent.php",sjPath:l.staticJavascriptPath||e.nexus+"/"+l.client+"/code/",alLoc:l.alertLocation||e.nexus+"/alerts/a.gif",
publishPath:l.publishPath,isPublic:l.isPublic,client:l.client,clientId:l.clientId,enableTagAuditBeacon:l.enableTagAuditBeacon,beaconSamplingSeedValue:l.beaconSamplingSeedValue||-1};e.ruleList=[];e.allDeploymentIds=[];e.runDeploymentIds=[];e.runRuleIds=[];e.exceptionList=[];e.ensightenVariables={};e.test=function(a){if(!(a.executionData.hasRun||a.executionData.runTime&&0<a.executionData.runTime.length)){for(var b=0;b<a.dependencies.length;b++)if(!1===a.dependencies[b]())return;a.execute()}};m.prototype=
Error();m.prototype||(m.prototype={});m.prototype.constructor=m;e.DependencyNotAvailableException=m;n.prototype=Error();n.prototype||(n.prototype={});n.prototype.constructor=n;e.BeaconException=n;e.checkForInvalidDependencies=function(a,b,d,f){for(a=0;a<d.length;a++)if("DEPENDENCYNEVERAVAILABLE"===d[a])return c.currentRuleId=this.id,c.currentDeploymentId=this.deploymentId,c.reportException(new e.DependencyNotAvailableException(f[a])),b&&-1!==b&&e.allDeploymentIds.push(b),!0;return!1};c.currentRuleId=
-1;c.currentDeploymentId=-1;c.reportedErrors=[];c.reportedAlerts=[];c.AF=[];c._serverTime="";c._clientIP="";c.sampleBeacon=function(){var a=!1;try{var b=(e.currSec||0)%20,d=e.options.beaconSamplingSeedValue;-1===d?a=!0:0!==b&&0===d%b&&(a=!0)}catch(f){}return a};c.getServerComponent=function(a){c.callOnGetServerComponent();c.insertScript(window.location.protocol+"//"+e.options.scLoc,!1,a||!0)};c.setVariable=function(a,b){e.ensightenVariables[a]=b};c.getVariable=function(a){return a in e.ensightenVariables?
e.ensightenVariables[a]:null};c.testAll=function(){for(var a=0;a<e.ruleList.length;a++)e.test(e.ruleList[a])};c.executionState={DOMParsed:!1,DOMLoaded:!1,dataDefinitionComplete:!1,conditionalRules:!1,readyForServerComponent:!1};c.reportException=function(a){a.timestamp=(new Date).getTime();e.exceptionList.push(a);a=window.location.protocol+"//"+e.options.erLoc+"?msg="+encodeURIComponent(a.message||"")+"&lnn="+encodeURIComponent(a.lineNumber||a.line||-1)+"&fn="+encodeURIComponent(a.fileName||"")+"&cid="+
encodeURIComponent(e.options.clientId||-1)+"&client="+encodeURIComponent(e.options.client||"")+"&publishPath="+encodeURIComponent(e.options.publishPath||"")+"&rid="+encodeURIComponent(c.currentRuleId||-1)+"&did="+encodeURIComponent(c.currentDeploymentId||-1)+"&errorName="+encodeURIComponent(a.name||"");a=c.imageRequest(a);a.timestamp=(new Date).getTime();this.reportedErrors.push(a)};c.Rule=function(a){this.execute=function(){this.executionData.runTime.push(new Date);c.currentRuleId=this.id;c.currentDeploymentId=
this.deploymentId;try{this.code()}catch(b){window[ensightenOptions.ns].reportException(b)}finally{this.executionData.hasRun=!0,-1!==this.deploymentId&&(e.runDeploymentIds.push(this.deploymentId),e.runRuleIds.push(this.id)),c.testAll()}};this.id=a.id;this.deploymentId=a.deploymentId;this.dependencies=a.dependencies||[];this.code=a.code;this.executionData={hasRun:!1,runTime:[]}};c.registerRule=function(a){if(c.getRule(a.id)&&-1!==a.id)return!1;e.ruleList.push(a);-1!==a.deploymentId&&e.allDeploymentIds.push(a.deploymentId);
c.testAll();return!0};c.getRule=function(a){for(var b=0;b<e.ruleList.length;b++)if(e.ruleList[b].id===a)return e.ruleList[b];return!1};c.getRuleList=function(){return e.ruleList};c.clearRuleList=function(){e.ruleList=[]};c.getAllDeploymentIds=function(){return e.allDeploymentIds};c.getRunRuleIds=function(){return e.runRuleIds};c.getRunDeploymentIds=function(){return e.runDeploymentIds};c.hasRuleRun=function(a){return(a=c.getRule(a))?a.executionData.hasRun:!1};e.toTwoChar=function(a){return(2===a.toString().length?
"":"0")+a};c.Alert=function(a){var b=new Date;b=b.getFullYear()+"-"+e.toTwoChar(b.getMonth())+"-"+e.toTwoChar(b.getDate())+" "+e.toTwoChar(b.getHours())+":"+e.toTwoChar(b.getMinutes())+":"+e.toTwoChar(b.getSeconds());this.severity=a.severity||1;this.subject=a.subject||"";this.type=a.type||1;this.ruleId=a.ruleId||-1;this.severity=encodeURIComponent(this.severity);this.date=encodeURIComponent(b);this.subject=encodeURIComponent(this.subject);this.type=encodeURIComponent(this.type)};c.generateAlert=function(a){a=
c.imageRequest(window.location.protocol+"//"+e.options.alLoc+"?d="+a.date+"&su="+a.subject+"&se="+a.severity+"&t="+a.type+"&cid="+e.options.clientId+"&client="+e.options.client+"&publishPath="+e.options.publishPath+"&rid="+c.currentRuleId+"&did="+c.currentDeploymentId);a.timestamp=(new Date).getTime();this.reportedAlerts.push(a)};c.imageRequest=function(a){var b=new Image(0,0);b.src=a;return b};c.insertScript=function(a,b,d){var f=document.getElementsByTagName("script"),g;if(void 0!==b?b:1)for(g=
0;g<f.length;g++)if(f[g].src===a&&f[g].readyState&&/loaded|complete/.test(f[g].readyState))return;if(d){d=1==d&&"object"==typeof c.scDataObj?c.scDataObj:d;e.rand=Math.random()*("1E"+(10*Math.random()).toFixed(0));b=window.location.href;"object"===typeof d&&d.PageID&&(b=d.PageID,delete d.PageID);if("object"===typeof d)for(g in d){g=~b.indexOf("#")?b.slice(b.indexOf("#"),b.length):"";b=b.slice(0,g.length?b.length-g.length:b.length);b+=~b.indexOf("?")?"&":"?";for(k in d)b+=k+"="+d[k]+"&";b=b.slice(0,
-1)+g;break}a=a+"?namespace="+(ensightenOptions.ns+"&");a+="staticJsPath="+ensightenOptions.staticJavascriptPath+"&";a+="publishedOn="+ensightenOptions.generatedOn+"&";a+="ClientID="+encodeURIComponent(e.options.clientId)+"&PageID="+encodeURIComponent(b)}(function(h,p,u){var r=p.head||p.getElementsByTagName("head");setTimeout(function(){if("item"in r){if(!r[0]){setTimeout(arguments.callee,25);return}r=r[0]}var t=p.createElement("script");t.src=u;t.onload=t.onerror=function(){this.addEventListener&&
(this.readyState="loaded")};r.insertBefore(t,r.firstChild)},0)})(window,document,a)};c.loadScriptCallback=function(a,b,d){var f=document.getElementsByTagName("script"),g;d=f[0];for(g=0;g<f.length;g++)if(f[g].src===a&&f[g].readyState&&/loaded|complete/.test(f[g].readyState))try{b()}catch(h){window[ensightenOptions.ns].reportException(h)}finally{return}f=document.createElement("script");f.type="text/javascript";f.async=!0;f.src=a;f.onerror=function(){this.addEventListener&&(this.readyState="loaded")};
f.onload=f.onreadystatechange=function(){if(!this.readyState||"complete"===this.readyState||"loaded"===this.readyState){this.onload=this.onreadystatechange=null;this.addEventListener&&(this.readyState="loaded");try{b.call(this)}catch(h){window[ensightenOptions.ns].reportException(h)}}};d.parentNode.insertBefore(f,d)};c.insertPageFiles=function(a){var b=0,d=0,f=function(){d==a.length-1&&window[ensightenOptions.ns].callOnPageSpecificCompletion();d++};for(b=0;b<a.length;++b)window[ensightenOptions.ns].loadScriptCallback(a[b],
f)};c.unobtrusiveAddEvent=function(a,b,d){try{var f=a[b]?a[b]:function(){};a[b]=function(){d.apply(this,arguments);return f.apply(this,arguments)}}catch(g){window[ensightenOptions.ns].reportException(g)}};c.anonymous=function(a,b){return function(){try{c.currentRuleId=b?b:"anonymous",a()}catch(d){window[ensightenOptions.ns].reportException(d)}}};c.setCurrentRuleId=function(a){c.currentRuleId=a};c.setCurrentDeploymentId=function(a){c.currentDeploymentId=a};c.bindImmediate=function(a,b,d){if("function"===
typeof a)a=new c.Rule({id:b||-1,deploymentId:d||-1,dependencies:[],code:a});else if("object"!==typeof a)return!1;c.registerRule(a)};c.bindDOMParsed=function(a,b,d){if("function"===typeof a)a=new c.Rule({id:b||-1,deploymentId:d||-1,dependencies:[function(){return window[ensightenOptions.ns].executionState.DOMParsed}],code:a});else if("object"!==typeof a)return!1;c.registerRule(a)};c.bindDOMLoaded=function(a,b,d){if("function"===typeof a)a=new c.Rule({id:b||-1,deploymentId:d||-1,dependencies:[function(){return window[ensightenOptions.ns].executionState.DOMLoaded}],
code:a});else if("object"!==typeof a)return!1;c.registerRule(a)};c.bindPageSpecificCompletion=function(a,b,d){if("function"===typeof a)a=new c.Rule({id:b||-1,deploymentId:d||-1,dependencies:[function(){return window[ensightenOptions.ns].executionState.conditionalRules}],code:a});else if("object"!==typeof a)return!1;c.registerRule(a)};c.bindOnGetServerComponent=function(a,b,d){if("function"===typeof a)a=new c.Rule({id:b||-1,deploymentId:d||-1,dependencies:[function(){return window[ensightenOptions.ns].executionState.readyForServerComponent}],
code:a});else if("object"!==typeof a)return!1;c.registerRule(a)};c.bindDataDefinitionComplete=function(a,b,d){if("function"===typeof a)a=new c.Rule({id:b||-1,deploymentId:d||-1,dependencies:[function(){return window[ensightenOptions.ns].executionState.dataDefinitionComplete}],code:a});else if("object"!==typeof a)return!1;c.registerRule(a)};c.checkHasRun=function(a){if(0===a.length)return!0;for(var b,d=0;d<a.length;++d)if(b=c.getRule(parseInt(a[d],10)),!b||!b.executionData.hasRun)return!1;return!0};
c.bindDependencyImmediate=function(a,b,d,f,g){var h=[];if(!e.checkForInvalidDependencies(b,f,d,g)){h.push(function(){return window[ensightenOptions.ns].checkHasRun(d)});if("function"===typeof a)a=new c.Rule({id:b||-1,deploymentId:f||-1,dependencies:h,code:a});else if("object"!==typeof a)return!1;c.registerRule(a)}};c.bindDependencyDOMLoaded=function(a,b,d,f,g){var h=[];if(!e.checkForInvalidDependencies(b,f,d,g)){h.push(function(){return window[ensightenOptions.ns].executionState.DOMLoaded});h.push(function(){return window[ensightenOptions.ns].checkHasRun(d)});
if("function"===typeof a)a=new c.Rule({id:b||-1,deploymentId:f||-1,dependencies:h,code:a});else if("object"!==typeof a)return!1;c.registerRule(a)}};c.bindDependencyDOMParsed=function(a,b,d,f,g){var h=[];if(!e.checkForInvalidDependencies(b,f,d,g)){h.push(function(){return window[ensightenOptions.ns].executionState.DOMParsed});h.push(function(){return window[ensightenOptions.ns].checkHasRun(d)});if("function"===typeof a)a=new c.Rule({id:b||-1,deploymentId:f||-1,dependencies:h,code:a});else if("object"!==
typeof a)return!1;c.registerRule(a)}};c.bindDependencyPageSpecificCompletion=function(a,b,d,f,g){var h=[];if(!e.checkForInvalidDependencies(b,f,d,g)){h.push(function(){return window[ensightenOptions.ns].executionState.conditionalRules});h.push(function(){return window[ensightenOptions.ns].checkHasRun(d)});if("function"===typeof a)a=new c.Rule({id:b||-1,deploymentId:f||-1,dependencies:h,code:a});else if("object"!==typeof a)return!1;c.registerRule(a)}};c.bindDependencyOnGetServerComponent=function(a,
b,d,f,g){var h=[];if(!e.checkForInvalidDependencies(b,f,d,g)){h.push(function(){return window[ensightenOptions.ns].executionState.readyForServerComponent});h.push(function(){return window[ensightenOptions.ns].checkHasRun(d)});if("function"===typeof a)a=new c.Rule({id:b||-1,deploymentId:f||-1,dependencies:h,code:a});else if("object"!==typeof a)return!1;c.registerRule(a)}};c.bindDependencyPageSpecificCompletion=function(a,b,d,f,g){var h=[];if(!e.checkForInvalidDependencies(b,f,d,g)){h.push(function(){return window[ensightenOptions.ns].executionState.dataDefinitionComplete});
h.push(function(){return window[ensightenOptions.ns].checkHasRun(d)});if("function"===typeof a)a=new c.Rule({id:b||-1,deploymentId:f||-1,dependencies:h,code:a});else if("object"!==typeof a)return!1;c.registerRule(a)}};c.dataDefintionIds=[];c.dataDefinitions=[];c.pageSpecificDataDefinitionsSet=!1;c.setPageSpecificDataDefinitionIds=function(a){for(var b=a?a.length:0,d=0;d<b;d++){var f=a[d];if(Array.prototype.indexOf)-1==c.dataDefinitionIds.indexOf(f)&&c.dataDefinitionIds.push(f);else{for(var g=!1,h=
c.dataDefinitionIds.length,p=0;p<h;p++)if(c.dataDefinitionIds[p]===f){g=!0;break}g||c.dataDefinitionIds.push(f)}}c.pageSpecificDataDefinitionsSet=!0;q()};c.DataDefinition=function(a,b){this.id=a;this.registrationFn=b;this.endRegistrationTime=this.startRegistrationTime=null;this.startRegistration=function(){this.startRegistrationTime=new Date};this.endRegistration=function(){this.endRegistrationTime=new Date}};c.registerDataDefinition=function(a,b){var d=c.dataDefinitions[b];d||(d=new c.DataDefinition(b,
a),c.dataDefinitions[b]=d);d.startRegistrationTime||(d.startRegistration(),d.registrationFn(),d.endRegistration());c.pageSpecificDataDefinitionsSet&&q()};c.callOnDataDefintionComplete=function(){c.executionState.dataDefinitionComplete=!0;c.testAll()};c.callOnDOMParsed=function(){window[ensightenOptions.ns].executionState.DOMParsed=!0;window[ensightenOptions.ns].testAll()};c.callOnDOMLoaded=function(){window[ensightenOptions.ns].executionState.DOMParsed=!0;window[ensightenOptions.ns].executionState.DOMLoaded=
!0;window[ensightenOptions.ns].testAll()};c.callOnPageSpecificCompletion=function(){for(var a=document.getElementsByTagName("script"),b=0,d=a.length;b<d;b++)if(a[b].src&&a[b].src.match(/\.ensighten\.com\/(.+?)\/code\/.*/i)&&"loaded"!=a[b].readyState&&"complete"!=a[b].readyState){setTimeout(window[ensightenOptions.ns].callOnPageSpecificCompletion,50);return}setTimeout(function(){window[ensightenOptions.ns].executionState.conditionalRules=!0;window[ensightenOptions.ns].testAll()},1)};c.callOnGetServerComponent=
function(){window[ensightenOptions.ns].executionState.readyForServerComponent=!0;window[ensightenOptions.ns].testAll()};c.hasDOMParsed=function(){return window[ensightenOptions.ns].executionState.DOMParsed};c.hasDOMLoaded=function(){return window[ensightenOptions.ns].executionState.DOMLoaded};c.hasPageSpecificCompletion=function(){return window[ensightenOptions.ns].executionState.conditionalRules};var v=function(){var a=[],b=!1,d=!1;return{add:function(f){b&&!d?f():"function"==typeof f&&(a[a.length]=
f)},exec:function(){d=!0;do{var f=a;a=[];b=!0;for(var g=0;g<f.length;g++)try{f[g].call(window)}catch(h){window[ensightenOptions.ns].reportException(h)}}while(0<a.length);d=!1},haveRun:function(){return b}}};c.new_fArray=function(){return v()};e.timer=null;(function(){function a(f,g){return function(){f.apply(g,arguments)}}window.console||(window.console={});var b=window.console;if(!b.log)if(window.log4javascript){var d=log4javascript.getDefaultLogger();b.log=a(d.info,d);b.debug=a(d.debug,d);b.info=
a(d.info,d);b.warn=a(d.warn,d);b.error=a(d.error,d)}else b.log=function(){};b.debug||(b.debug=b.log);b.info||(b.info=b.log);b.warn||(b.warn=b.log);b.error||(b.error=b.log)})();document.addEventListener?(-1<navigator.userAgent.indexOf("AppleWebKit/")?e.timer=window.setInterval(function(){/loaded|interactive|complete/.test(document.readyState)&&(clearInterval(e.timer),c.callOnDOMParsed())},50):document.addEventListener("DOMContentLoaded",c.callOnDOMParsed,!1),window.addEventListener("load",c.callOnDOMLoaded,
!1)):(setTimeout(function(){var a=window.document;(function(){try{if(!document.body)throw"continue";a.documentElement.doScroll("left")}catch(b){setTimeout(arguments.callee,15);return}window[ensightenOptions.ns].callOnDOMParsed()})()},1),window.attachEvent("onload",function(){window[ensightenOptions.ns].callOnDOMLoaded()}));document.readyState&&"complete"===document.readyState&&(c.executionState.DOMParsed=!0,c.executionState.DOMLoaded=!0);"true"===e.options.enableTagAuditBeacon&&c.sampleBeacon()&&
window.setTimeout(function(){if(window[ensightenOptions.ns]&&!window[ensightenOptions.ns].mobilePlatform)try{for(var a=[],b,d,f,g,h=0;h<e.ruleList.length;++h)d=e.ruleList[h],f=d.executionData.hasRun?"1":"0",g=d.deploymentId.toString()+"|"+d.id.toString()+"|"+f,a.push(g);b="["+a.join(";")+"]";var p=window.location.protocol+"//"+e.nexus+"/"+encodeURIComponent(l.client)+"/"+encodeURIComponent(l.publishPath)+"/TagAuditBeacon.rnc?cid="+encodeURIComponent(l.clientId)+"&data="+b+"&idx=0&r="+e.rand;c.imageRequest(p)}catch(u){c.currentRuleId=
-1,c.currentDeploymentId=-1,a=new e.BeaconException(u),window[ensightenOptions.ns].reportException(a)}},3E3);window.setInterval(c.testAll,e.options.interval);return c}(ensightenOptions);
"true"===ensightenOptions.enablePagePerfBeacon&&window[ensightenOptions.ns]&&window[ensightenOptions.ns].sampleBeacon()&&window[ensightenOptions.ns].bindDOMParsed(function(){if(!window[ensightenOptions.ns].mobilePlatform){var l=window.performance;if(l){l=l.timing||{};var m=l.navigationStart||0,n={connectEnd:"ce",connectStart:"cs",domComplete:"dc",domContentLoadedEventEnd:"dclee",domContentLoadedEventStart:"dcles",domInteractive:"di",domLoading:"dl",domainLookupEnd:"dle",domainLookupStart:"dls",fetchStart:"fs",
loadEventEnd:"lee",loadEventStart:"les",redirectEnd:"rede",redirectStart:"reds",requestStart:"reqs",responseStart:"resps",responseEnd:"respe",secureConnectionStart:"scs",unloadEventStart:"ues",unloadEventEnd:"uee"};var q="&ns="+encodeURIComponent(l.navigationStart);for(var e in n)if(void 0!==l[e]){var c=l[e]-m;q+="&"+n[e]+"="+(0<c?encodeURIComponent(c):0)}else q+="&"+n[e]+"=-1";window[ensightenOptions.ns].timing=q;e=ensightenOptions.nexus||"nexus.ensighten.com";l=ensightenOptions.staticJavascriptPath||
"";q=l.indexOf("/",0);m=l.indexOf("/code/");l=l.substring(q,m)+"/perf.rnc";l+="?cid="+encodeURIComponent(ensightenOptions.clientId)+window[ensightenOptions.ns].timing;window[ensightenOptions.ns].imageRequest("//"+e+l)}}});
		Marketing.dataDefinitionIds = [];Marketing.bindDependencyImmediate(function(){var Bootstrapper=window["Marketing"];var ensightenOptions=Marketing.ensightenOptions},3774277,[3774271],610323,[726535]);
Marketing.bindDependencyImmediate(function(){var Bootstrapper=window["Marketing"];var ensightenOptions=Marketing.ensightenOptions;var init=function(){Marketing.UDO.fl_loaded=false;Marketing.insertScript("https://www.googletagmanager.com/gtag/js?id\x3dDC-9632645");dell_marketing_util.custom_marketing_event("fl_loaded");Marketing.UDO.fl_loaded=true;window.dataLayer=window.dataLayer||[];window.gtag=function(){dataLayer.push(arguments)};if(Marketing.UDO.country=="es"){gtag("consent","default",{"ad_storage":"denied",
"analytics_storage":"denied","wait_for_update":500,"region":["ES"]});gtag("set","url_passthrough",true);if(window.privacyMarketing)gtag("consent","update",{"ad_storage":"granted","analytics_storage":"granted"});else window.addEventListener("privacy-marketing-consent",function(e){gtag("consent","update",{"ad_storage":"granted","analytics_storage":"granted"})})}gtag("js",new Date);gtag("config","DC-9632645");gtag("config","DC-9632921");gtag("config","DC-9632648")};if(window.privacyReady)!window.privacyGPC&&
init();else window.addEventListener("privacy-ready",function(){!window.privacyGPC&&init()})},3774851,[3815478],726824,[726737]);
Marketing.bindImmediate(function(){var Bootstrapper=window["Marketing"];var ensightenOptions=Marketing.ensightenOptions;(function(){function s(e,t,n){var r=t=="blur"||t=="focus";e.element.addEventListener(t,n,r)}function o(e){e.preventDefault();e.stopPropagation()}function u(t){if(e)return e;if(t.matches)e=t.matches;if(t.webkitMatchesSelector)e=t.webkitMatchesSelector;if(t.mozMatchesSelector)e=t.mozMatchesSelector;if(t.msMatchesSelector)e=t.msMatchesSelector;if(t.oMatchesSelector)e=t.oMatchesSelector;
if(!e)e=p.matchesSelector;return e}function a(element,n,r){if(n=="_root")return r;if(element===r)return;try{if(u(element).call(element,n))return element}catch(error){e=null;if(u(element).call(element,n))return element}if(element.parentNode){t++;return a(element.parentNode,n,r)}}function f(e,t,n,i){if(!r[e.id])r[e.id]={};if(!r[e.id][t])r[e.id][t]={};if(!r[e.id][t][n])r[e.id][t][n]=[];r[e.id][t][n].push(i)}function l(e,t,n,i){if(!i&&!n){r[e.id][t]={};return}if(!i){delete r[e.id][t][n];return}for(var s=
0;s<r[e.id][t][n].length;s++)if(r[e.id][t][n][s]===i){r[e.id][t][n].pop(s,1);break}}function c(e,n,s){if(!r[e][s])return;var o=n.target||n.srcElement,u,f,l={},c=0,h=0;t=0;for(u in r[e][s])if(r[e][s].hasOwnProperty(u)){f=a(o,u,i[e].element);if(f&&p.matchesEvent(s,i[e].element,f,u=="_root",n)){t++;r[e][s][u].match=f;l[t]=r[e][s][u]}}n.stopPropagation=function(){n.cancelBubble=true};for(c=0;c<=t;c++)if(l[c])for(h=0;h<l[c].length;h++){if(l[c][h].call(l[c].match,n)===false){p.cancel(n);return}if(n.cancelBubble)return}}
function h(e,t,n,i){function u(e){return function(t){c(s,t,e)}}if(!(e instanceof Array))e=[e];if(!n&&typeof t=="function"){n=t;t="_root"}var s=this.id,o;for(o=0;o<e.length;o++){if(!r[s]||!r[s][e[o]])p.addEvent(this,e[o],u(e[o]));if(i){l(this,e[o],t,n);continue}f(this,e[o],t,n)}return this}function p(e,t){if(typeof e=="string"&&typeof t=="function"||typeof t=="string")p(document).on(arguments[0],arguments[1],arguments[2],arguments[3]||false);if(!(this instanceof p)){for(var r in i)if(i[r].element===
e)return i[r];n++;i[n]=new p(e,n);i[n]._on=i[n].on;i[n].on=function(e,t,n,r){var i=typeof t=="function"?t:n,s=typeof t=="function"?n||false:r||false;if(!s)return this._on.call(this,e,t,n);else{var o=[e];if(typeof t=="string")o.push(t);o.push(function(e){return function(t){if(!t.defaultPrevented)Bootstrapper.Delegate.load(this,s);if(typeof t.preventDefault!="undefined")t.preventDefault();else t.returnValue=false;e.call(this)}}(i));this._on.apply(this,o)}};return i[n]}this.element=e;this.id=t}var e,
t=0,n=0,r={},i={};_delay=750;p.prototype.on=function(e,t,n){return h.call(this,e,t,n)};p.prototype.off=function(e,t,n){return h.call(this,e,t,n,true)};p.matchesSelector=function(){};p.cancel=o;p.addEvent=s;p.matchesEvent=function(){return true};p.load=function(e,t){var n=typeof t=="number"?parseInt(t):750;setTimeout(function(e,t){return function(){if(e.nodeName&&"a"==e.nodeName.toLowerCase()){if(t&&/^javascript\s*:/.test(t))return(new Function(unescape(t))).call(window);else if(e.target&&/_blank|_new/i.test(e.target))return true;
if(t)window.location.href=t}}}(e,e.href||""),n)};Bootstrapper.Delegate=p})();(function(e){var t=e.addEvent;e.addEvent=function(e,n,r){if(e.element.addEventListener)return t(e,n,r);if(n=="focus")n="focusin";if(n=="blur")n="focusout";e.element.attachEvent("on"+n,r)};e.simpleMatchesSelector=function(e){if(e.charAt(0)===".")return(" "+this.className+" ").indexOf(" "+e.slice(1)+" ")>-1;if(e.charAt(0)==="#")return this.id===e.slice(1);return this.tagName.toUpperCase()===e.toUpperCase()};e.matchesSelector=
function(t){if(!~t.indexOf(" ")&&!~t.indexOf("\x3e"))return e.simpleMatchesSelector.call(this,t);else{var n=this,r=t.split(" ").reverse();while(r.length){var i=r.shift();if(~i.indexOf("\x3e")){i=i.split("\x3e").reverse();while(i.length){tempSel=i.shift();if(e.simpleMatchesSelector.call(n,tempSel))n=n.parentNode;else return false}if(!r.length)return true}else while(n!=document){var s=e.simpleMatchesSelector.call(n,i);if(n.parentNode)n=n.parentNode;n=n.parentnode?n.parentnode:document;if(s){if(!r.length)return true;
break}}}return false}};e.cancel=function(e){if(e.preventDefault)e.preventDefault();if(e.stopPropagation)e.stopPropagation();e.returnValue=false;e.cancelBubble=true}})(Bootstrapper.Delegate);Bootstrapper.on=Bootstrapper.Delegate;window.dell_marketing_util={};Dell=window.Dell||{};Dell.Metrics=Dell.Metrics||{};Dell.Metrics.sc=Dell.Metrics.sc||{};dell_marketing_util.getCookie=function(cookie_name){var results=document.cookie.match("(^|;) ?"+cookie_name+"\x3d([^;]*)(;|$)");if(results)return unescape(results[2]);
else return null};dell_marketing_util.setCookie=function(name,val,opts){var cookie;cookie=name+"\x3d"+val;if(opts){if(opts.expDate)cookie+="; expires\x3d"+opts.expDate.toGMTString();if(opts.path)cookie+="; path\x3d"+escape(opts.path);if(opts.domain)cookie+="; domain\x3d"+escape(opts.domain);if(opts.secure)cookie+="; secure"}return document.cookie=cookie};dell_marketing_util.getParameterByName=function(name,qstring){name=name.replace(/[\[]/,"\\[").replace(/[\]]/,"\\]");var regex=new RegExp("[\\?\x26]"+
name+"\x3d([^\x26#]*)"),results=regex.exec(qstring);return results===null?"":decodeURIComponent(results[1].replace(/\+/g," "))};dell_marketing_util.iFrame=function(){try{return window.self!==window.top}catch(e){return true}};dell_marketing_util.debug=function(errorMessage){if(Marketing.ensightenOptions.publishPath==="marketingdev"||dell_marketing_util.getParameterByName("mdebug",location.search)==="true"||dell_marketing_util.getCookie("mdebug")==="true")console.error(errorMessage)};dell_marketing_util.getscMap=
function(key){var scMap=Dell.Metrics.sc;return typeof scMap[key]!="undefined"?typeof scMap[key]==="string"?scMap[key].toLowerCase():scMap[key]:"undefined"};if(dell_marketing_util.getscMap("country")!=="undefined"&&dell_marketing_util.getscMap("language")!=="undefined"&&dell_marketing_util.getscMap("segment")!=="undefined"&&dell_marketing_util.getscMap("customerset")!=="undefined"&&dell_marketing_util.getscMap("cms")!=="undefined"){Marketing.scDataObj.country=dell_marketing_util.getscMap("country");
Marketing.scDataObj.language=dell_marketing_util.getscMap("language");Marketing.scDataObj.segment=dell_marketing_util.getscMap("segment");Marketing.scDataObj.cset=dell_marketing_util.getscMap("customerset");Marketing.scDataObj.categoryid=dell_marketing_util.getscMap("categoryid");Marketing.scDataObj.cms=dell_marketing_util.getscMap("cms");Marketing.scDataObj.page=dell_marketing_util.getscMap("wacontroller");Marketing.scDataObj.module=dell_marketing_util.getscMap("module")}else{var metaTags=document.getElementsByTagName("meta"),
metaName="",metaContent="",metaCount=0,metaLength=metaTags.length;Marketing.scDataObj=Marketing.scDataObj||{};for(metaCount;metaCount<metaLength;metaCount++){metaName=metaTags[metaCount].name||"";metaContent=metaTags[metaCount].content.toLowerCase()||"";if(/language/i.test(metaName))Marketing.scDataObj.language=metaContent;else if(/segment/i.test(metaName))Marketing.scDataObj.segment=metaContent;else if(/customerset/i.test(metaName))Marketing.scDataObj.cset=metaContent;else if(/documentcountrycode|country/i.test(metaName))Marketing.scDataObj.country=
metaContent;else if(/generator/i.test(metaName)){var cmsVal="other";if(/^storm/i.test(metaContent))cmsVal="Storm";else if(/^ng/i.test(metaContent))cmsVal="NG";else if(/^(stp|transactional)/i.test(metaContent))cmsVal="STP";else if(/^mse/i.test(metaContent))cmsVal="FUELSPA";else if(/^build:\s\d+\./i.test(metaContent))cmsVal=metaContent.split("Built")[0].replace(/(\s|:)/g,"");Marketing.scDataObj.cms=cmsVal}}var location_href=window.location.href,lwp=dell_marketing_util.getCookie("lwp");if(typeof Marketing.scDataObj.cset===
"undefined")if(/cs=/i.test(location_href))Marketing.scDataObj.cset=dell_marketing_util.getParameterByName("cs",location_href);else Marketing.scDataObj.cset=dell_marketing_util.getParameterByName("cs",lwp);if(typeof Marketing.scDataObj.segment==="undefined")if(/\\?s=/i.test(location_href)||/&s=/i.test(location_href))Marketing.scDataObj.segment=dell_marketing_util.getParameterByName("s",location_href);else Marketing.scDataObj.segment=dell_marketing_util.getParameterByName("s",lwp);metaTags=null}},3774271,
726535);
Marketing.bindDependencyImmediate(function(){var Bootstrapper=window["Marketing"];var ensightenOptions=Marketing.ensightenOptions;try{if(!String.prototype.includes)String.prototype.includes=function(search,start){if(search instanceof RegExp)return false;if(start===undefined)start=0;return this.indexOf(search,start)!==-1};Marketing=Marketing||{};Marketing.UDO=Marketing.UDO||{};MarketingUdo=window.MarketingUdo||window.MasterTmsUdo||{};MarketingUdo.CJ=MarketingUdo.CJ||{};var searchStr=location.href;searchStr=
searchStr.replace(/ven(\d)=/ig,"ven$1\x3d");var ven1=dell_marketing_util.getParameterByName("ven1",searchStr);searchStr=searchStr.replace(/gacd=/ig,"gacd\x3d");var gacd=dell_marketing_util.getParameterByName("gacd",searchStr);searchStr=searchStr.replace(/clickid=/ig,"clickid\x3d");var clickid=dell_marketing_util.getParameterByName("clickid",searchStr);searchStr=searchStr.replace(/utm_source=Rakuten/ig,"rkt\x3dtrue");var rkt=dell_marketing_util.getParameterByName("rkt",searchStr);searchStr=searchStr.replace(/xtra=/ig,
"xtra\x3d");var xtra=dell_marketing_util.getParameterByName("xtra",searchStr);searchStr=searchStr.replace(/ranSiteID=/ig,"ransiteid\x3d");var ranSiteid=dell_marketing_util.getParameterByName("ransiteid",searchStr);searchStr=searchStr.replace(/ranMID=/ig,"ranmid\x3d");var ranMID=dell_marketing_util.getParameterByName("ranmid",searchStr);if(!dell_marketing_util.iFrame())if(sessionStorage.enspagecountFLT)sessionStorage.enspagecountFLT=Number(sessionStorage.enspagecountFLT)+1;else sessionStorage.enspagecountFLT=
1;var getStorageItem=sessionStorage.getItem("dellpublisher");var dellPublisher=getStorageItem||dell_marketing_util.getParameterByName("publisher",location.href);if(!getStorageItem&&dellPublisher)sessionStorage.setItem("dellpublisher",dellPublisher);var setAdCookies=function(){var exp,land,days;exp=new Date;land=new Date;days=90;exp.setTime(exp.getTime()+days*24*60*60*1E3);if(ven1){dell_marketing_util.setCookie("dellven",ven1,{domain:"dell.com",path:"/",expDate:exp,secure:true});dell_marketing_util.setCookie("dellland",
land.getTime(),{domain:"dell.com",path:"/",expDate:exp,secure:true})}if(ranSiteid){var ranSiteIdExp=new Date;var expDays=dell_marketing_util.getscMap("country")=="br"?10:90;ranSiteIdExp.setTime(ranSiteIdExp.getTime()+expDays*24*60*60*1E3);dell_marketing_util.setCookie("dellransiteid",ranSiteid,{domain:"dell.com",path:"/",expDate:ranSiteIdExp,secure:true});dell_marketing_util.setCookie("dellland",land.getTime(),{domain:"dell.com",path:"/",expDate:exp,secure:true})}if(ranMID)dell_marketing_util.setCookie("dellranmid",
ranMID,{domain:"dell.com",path:"/",expDate:exp,secure:true});if(gacd)dell_marketing_util.setCookie("dellgacd",gacd,{domain:"dell.com",path:"/",expDate:exp,secure:true});if(clickid)dell_marketing_util.setCookie("dellclickid",clickid,{domain:"dell.com",path:"/",expDate:exp,secure:true});if(rkt)dell_marketing_util.setCookie("RKT",rkt,{domain:"dell.com",path:"/",expDate:exp,secure:true});if(xtra){var xtraExp=new Date;var expDays=3;xtraExp.setTime(xtraExp.getTime()+expDays*24*60*60*1E3);dell_marketing_util.setCookie("dellxtra",
xtra,{domain:"dell.com",path:"/",expDate:xtraExp,secure:true})}};setAdCookies();var dellvenCookieVal=dell_marketing_util.getCookie("dellven")||"";dell_marketing_util.getUdoMap=function(key){if(MarketingUdo&&JSON.stringify(MarketingUdo.CJ)!=="{}")MarketingUdo=MarketingUdo;if(window.MasterTmsUdo&&JSON.stringify(window.MasterTmsUdo.CJ)!=="{}")MarketingUdo=window.MasterTmsUdo;var udoMap=MarketingUdo.CJ;return typeof udoMap[key]!="undefined"&&typeof udoMap[key]=="string"?udoMap[key].toLowerCase():udoMap[key]||
""};dell_marketing_util.custom_marketing_event=function(eventName){var event;if(document.createEvent){event=document.createEvent("Event");event.initEvent(eventName,true,true);event.eventName=eventName;window.dispatchEvent(event)}};dell_marketing_util.createIframe=function(name,src){src=src||"javascript:void(0)";var ifrm=document.createElement("iframe");ifrm.setAttribute("src",src);ifrm.setAttribute("name",name);ifrm.setAttribute("tabindex","-1");ifrm.setAttribute("aria-hidden",true);ifrm.style.visibility=
"hidden";ifrm.style.position="absolute";ifrm.style.bottom="0";ifrm.width="0";ifrm.height="0";ifrm.frameBorder="0";document.body.appendChild(ifrm)};dell_marketing_util.createElement=function(srcUrl,elem){var elemTag=document.createElement(elem);elemTag.src=srcUrl;elemTag.setAttribute("tabindex","-1");elemTag.setAttribute("aria-hidden",true);elemTag.async=true;elemTag.height="0";elemTag.width="0";elemTag.style.display="none";elemTag.style.position="absolute";elemTag.style.bottom="0";elemTag.frameBorder=
"0";top.document.body.appendChild(elemTag)};dell_marketing_util.getDpid=function(preserveFormat){var dpid=Dell.Metrics.sc.dpid||MarketingUdo.CJ.DPID;if(dpid){if(preserveFormat)return dpid.toString();return dpid.toString().replace(/-/gi,"")}return""};dell_marketing_util.serialProductList=function(){var serialProdList="";if(/9|100/.test(dell_marketing_util.getUdoMap("PROMOID"))){serialProdList=[];var cartData=Dell.Transactional?Dell.Transactional.Cart.Metrics.Data.Analytics.FlattenedItems:"",prodList=
dell_marketing_util.getUdoMap("PRODUCTLIST");for(var i=0;i<prodList.length;i++){var cartDataPrice=cartData?cartData[i].Price:prodList[i].AMT_AFTER_DISCOUNT;serialProdList.push(prodList[i].ITEM+":"+prodList[i].AMT+":"+prodList[i].QTY+":"+cartDataPrice)}return serialProdList.join("|")}return serialProdList};Marketing.UDO.readData=function(){Marketing.UDO.accountid=dell_marketing_util.getUdoMap("ACCOUNTID");Marketing.UDO.category=dell_marketing_util.getUdoMap("CATEGORY");Marketing.UDO.categorypath=dell_marketing_util.getUdoMap("CATEGORYPATH");
Marketing.UDO.cid=dell_marketing_util.getUdoMap("CID");Marketing.UDO.coupon=dell_marketing_util.getUdoMap("COUPON");Marketing.UDO.cseg=dell_marketing_util.getUdoMap("CSEG");Marketing.UDO.currency=dell_marketing_util.getUdoMap("CURRENCY");Marketing.UDO.deals=dell_marketing_util.getUdoMap("DEALS");Marketing.UDO.device=dell_marketing_util.getUdoMap("DEVICE");Marketing.UDO.discount=dell_marketing_util.getUdoMap("DISCOUNT");Marketing.UDO.emailhash=dell_marketing_util.getUdoMap("EMAILHASH");Marketing.UDO.family=
dell_marketing_util.getUdoMap("FAMILY");Marketing.UDO.ogid=dell_marketing_util.getUdoMap("OGID");Marketing.UDO.family=dell_marketing_util.getUdoMap("FAMILY");Marketing.UDO.ordercode=dell_marketing_util.getUdoMap("ORDERCODE");Marketing.UDO.platform=dell_marketing_util.getUdoMap("PLATFORM");Marketing.UDO.prodcat=dell_marketing_util.getUdoMap("PRODCAT");Marketing.UDO.product=dell_marketing_util.getUdoMap("PRODUCT");Marketing.UDO.productlist=dell_marketing_util.getUdoMap("PRODUCTLIST");Marketing.UDO.promoid=
dell_marketing_util.getUdoMap("PROMOID");Marketing.UDO.revenue=dell_marketing_util.getUdoMap("REVENUE");Marketing.UDO.type=dell_marketing_util.getUdoMap("TYPE");Marketing.UDO.shippingtax=dell_marketing_util.getUdoMap("SHIPPINGTAX");Marketing.UDO.totaltax=dell_marketing_util.getUdoMap("TOTALTAX");Marketing.UDO.country=Marketing.scDataObj.country;Marketing.UDO.language=Marketing.scDataObj.language;Marketing.UDO.segment=Marketing.scDataObj.segment;Marketing.UDO.user=dell_marketing_util.getUdoMap("USER")||
dell_marketing_util.getCookie("p13np")||"none";Marketing.UDO.dpid=dell_marketing_util.getDpid(true);Marketing.UDO.serialprodlist=dell_marketing_util.serialProductList();Marketing.UDO.loyalty=dellPublisher=="loyalty"?true:false;if(Marketing.UDO.currency.toLowerCase()==="usd")Marketing.UDO.usdrev=Marketing.UDO.revenue;else Marketing.UDO.usdrev=dell_marketing_util.getUdoMap("CONV_REVENUE");Marketing.UDO.udoReady=Marketing.scDataObj.cms=="olr"?false:true};Marketing.UDO.readData();window.addEventListener("datalayerReady",
function(){Marketing.UDO.readData();var ogid=dell_marketing_util.getscMap("ordergroupid");if(ogid!="undefined")Marketing.UDO.ogid=ogid;if(!Marketing.UDO.dpid&&Marketing.UDO.promoid=="100")Marketing.on("click",".dellmetrics-pp",function(){Marketing.UDO.dpid=dell_marketing_util.getDpid(true);Marketing.UDO.udoReady=true;dell_marketing_util.custom_marketing_event("udoReady")});else{Marketing.UDO.udoReady=true;dell_marketing_util.custom_marketing_event("udoReady")}});window.Pulse=window.Pulse||{runWidget:function(){dell_marketing_util.custom_marketing_event("datalayerReady");
return true}};window.addEventListener("hve",function(e){if((e.detail.type==="download"||e.detail.type==="document")&&window.location.hash.indexOf("overlay\x3d")>-1)Marketing.UDO.hveoverlay=true});Marketing.UDO.gacd=dell_marketing_util.getCookie("dellgacd")||"";Marketing.UDO.land=dell_marketing_util.getCookie("dellland")||"";Marketing.UDO.clickid=dell_marketing_util.getCookie("dellclickid")||"";Marketing.UDO.rkt=dell_marketing_util.getCookie("RKT")||"";Marketing.UDO.xtra=dell_marketing_util.getCookie("dellxtra")||
"";Marketing.UDO.ranSiteid=dell_marketing_util.getCookie("dellransiteid")||"";Marketing.UDO.ranMID=dell_marketing_util.getCookie("dellranmid")||"";Marketing.UDO.metafbp=dell_marketing_util.getCookie("_fbp")||"";Marketing.UDO.cjevent=dell_marketing_util.getCookie("cjevent")||dell_marketing_util.getCookie("CJE")||"";Marketing.UDO.ven1=dellvenCookieVal.split("|")[0]||"";Marketing.UDO.ven2=dell_marketing_util.getParameterByName("ven2",searchStr);Marketing.UDO.mcmid="";var adobe_mcmid=dell_marketing_util.getCookie("AMCV_4DD80861515CAB990A490D45%40AdobeOrg");
if(adobe_mcmid&&adobe_mcmid.indexOf("MCMID|")>-1)Marketing.UDO.mcmid=adobe_mcmid.split("MCMID|")[1].split("|")[0];Marketing.UDO.hve_mpv=function(srcUrl,elem){var elem=elem||"img";if(sessionStorage.enspagecountFLT==3)dell_marketing_util.createElement(srcUrl,elem)};Marketing.UDO.hve_download=function(srcUrl,elem){var elem=elem||"img";window.addEventListener("hve",function(e){Marketing.UDO.hveoverlay=false;if(e.detail.type==="download"||e.detail.type==="document")dell_marketing_util.createElement(srcUrl,
elem)});if(Marketing.UDO.hveoverlay)dell_marketing_util.createElement(srcUrl,elem)};Marketing.UDO.hve_contactUs=function(srcUrl,elem){var elem=elem||"img";window.addEventListener("hve",function(e){if(e.detail.type==="contactus")dell_marketing_util.createElement(srcUrl,elem)})};Marketing.UDO.hve_chat=function(srcUrl,elem){var elem=elem||"img";window.addEventListener("hve",function(e){if(e.detail.type==="chat")dell_marketing_util.createElement(srcUrl,elem)})};var video_hist=[];Marketing.UDO.hve_ytube=
function(srcUrl,elem){var elem=elem||"img";var parent=window.top;var doc=top.document;parent.addEventListener("hashchange",yt_video);yt_videos=top.document.querySelectorAll('a[href*\x3d"youtube"]');for(var i=0;i<yt_videos.length;i++)yt_videos[i].addEventListener("click",yt_video_handler);function yt_video_handler(e){var elemTag=document.createElement(elem);elemTag.src=srcUrl;elemTag.async=true;elemTag.height=1;elemTag.width=1;top.document.body.appendChild(elemTag);e.currentTarget.removeEventListener("click",
yt_video_handler)}function yt_video(){var hash=parent.location.hash;var img=document.createElement("img");var vid=hash.substring(hash.indexOf("video-overlay"),hash.length).split("\x3d")[1];if(video_hist.indexOf(vid)==-1)if(hash.indexOf("video-overlay")==-1)return;else if(hash.indexOf("video-overlay")!==-1){var elemTag=document.createElement(elem);elemTag.src=srcUrl;elemTag.height=1;elemTag.width=1;parent.document.body.appendChild(elemTag);video_hist.push(vid)}}};Marketing.UDO.hve_bc_start=function(srcUrl,
elem){var elem=elem||"img";if(typeof videojs!=="undefined"&&videojs.players)for(var v in videojs.players)videojs.players[v].ready(function(){var myplayer=this,userVideo=!myplayer.muted()||!myplayer.el_.hasAttribute("muted");if(userVideo)myplayer.on("start",function(){if(!myplayer.video_start){myplayer.video_50_percent=false;myplayer.video_80_percent=false;dell_marketing_util.createElement(srcUrl,elem)}})});else window.addEventListener("hve",function _handler(e){if(e.detail.type==="brightcove")Marketing.UDO.hve_bc_start(srcUrl,
elem)})};Marketing.UDO.hve_bc_50=function(srcUrl,elem){var elem=elem||"img";window.addEventListener("brightcove50",function(e){dell_marketing_util.createElement(srcUrl,elem)})};Marketing.UDO.hve_bc_80=function(srcUrl,elem){var elem=elem||"img";window.addEventListener("brightcove80",function(e){dell_marketing_util.createElement(srcUrl,elem)})};Marketing.UDO.hve_bc_end=function(srcUrl,elem){var elem=elem||"img";if(typeof videojs!=="undefined"&&videojs.players)for(var v in videojs.players)videojs.players[v].ready(function(){var myplayer=
this,userVideo=!myplayer.muted()||!myplayer.el_.hasAttribute("muted");if(userVideo)myplayer.on("ended",function(){dell_marketing_util.createElement(srcUrl,elem);myplayer.video_start=false})});else window.addEventListener("hve",function _handler(e){if(e.detail.type==="brightcove")Marketing.UDO.hve_bc_end(srcUrl,elem)})};Marketing.UDO.hve_bcove=function(srcUrl,elem){var elem=elem||"img";Marketing.UDO.hve_bc_start(srcUrl,elem);Marketing.UDO.hve_bc_50(srcUrl,elem);Marketing.UDO.hve_bc_80(srcUrl,elem);
Marketing.UDO.hve_bc_end(srcUrl,elem)};Marketing.UDO.hve_podcast_listen=function(srcUrl,elem){var elem=elem||"img";window.addEventListener("hve",function(e){if(e.detail.type==="podcast_listen")dell_marketing_util.createElement(srcUrl,elem)})};Marketing.UDO.hve_podcast_subscribe=function(srcUrl,elem){var elem=elem||"img";window.addEventListener("hve",function(e){if(e.detail.type==="podcast_subscribe")dell_marketing_util.createElement(srcUrl,elem)})};Marketing.UDO.hve_rfq_submit=function(srcUrl,elem){var elem=
elem||"img";window.addEventListener("hve",function(e){if(e.detail.type==="rfq_submit")dell_marketing_util.createElement(srcUrl,elem)})};Marketing.UDO.hve_ion_submit=function(srcUrl,elem){var elem=elem||"img";if(/liveball.*completed/gi.test(dell_marketing_util.getscMap("pagename")))dell_marketing_util.createElement(srcUrl,elem)};Marketing.UDO.hve_gated_submit=function(srcUrl,elem){var elem=elem||"img";window.addEventListener("hve",function(e){if(e.detail.type==="gated_submit")dell_marketing_util.createElement(srcUrl,
elem)})};Marketing.UDO.hve_podcasts=function(srcUrl,elem){Marketing.UDO.hve_podcast_listen(srcUrl,elem)};Marketing.UDO.hve_social=function(srcUrl,elem){var elem=elem||"img";window.addEventListener("hve",function(e){if(e.detail.type==="share")dell_marketing_util.createElement(srcUrl,elem)})};var custom_marketing_event=function(eventName){var event;if(document.createEvent){event=document.createEvent("Event");event.initEvent(eventName,true,true);event.eventName=eventName;window.dispatchEvent(event)}};
Marketing.UDO.bc_timer=function(){if(typeof videojs!=="undefined"&&videojs.players)for(v in videojs.players)videojs.players[v].ready(function(){var myplayer=this,userVideo=!myplayer.muted()||!myplayer.el_.hasAttribute("muted");if(userVideo){var checkPlayTime=function(){if(myplayer.currentTime()==0)myplayer.video_start=false;else{if(!myplayer.video_start)myplayer.trigger("start");myplayer.video_start=myplayer.hasStarted_}var duration=myplayer.duration();var percentRemaining=Math.ceil(myplayer.remainingTime()*
100/duration);if(percentRemaining<50&&!myplayer.video_50_percent){myplayer.video_50_percent=true;dell_marketing_util.custom_marketing_event("brightcove50")}else if(percentRemaining<20&&!myplayer.video_80_percent){myplayer.video_80_percent=true;dell_marketing_util.custom_marketing_event("brightcove80")}};myplayer.off("timeupdate",function(){checkPlayTime()});myplayer.on("timeupdate",function(){checkPlayTime()})}});else window.addEventListener("hve",function _handler(e){if(e.detail.type==="brightcove")Marketing.UDO.bc_timer()})};
Marketing.UDO.bc_timer();Marketing.UDO.perfTimingStart=function(id){if(performance&&performance.mark)performance.mark("ensighten-marketing-"+id+"-start")};Marketing.UDO.perfTimingEnd=function(id){if(performance&&performance.mark&&performance.measure){var mark="ensighten-marketing-"+id;performance.mark(mark+"-end");performance.measure(mark,mark+"-start",mark+"-end")}};Marketing.insertScriptNonce=function(src,id,name){var nonceAttr=document.querySelector("script[src*\x3d'Bootstrap.js']").nonce;var tag=
document.createElement("script");tag.type="text/javascript";tag.async=true;tag.src=src;if(id)tag.id=id;if(name)tag.setAttribute("name",name);if(nonceAttr)tag.setAttribute("nonce",nonceAttr);var scriptTag=document.getElementsByTagName("script")[0];scriptTag.parentNode.insertBefore(tag,scriptTag)}}catch(e){dell_marketing_util.debug(e)}},3815478,[3774271],726737,[726535]);
Marketing.bindDependencyImmediate(function(){var Bootstrapper=window["Marketing"];var ensightenOptions=Marketing.ensightenOptions;try{var fire_pulse=function(){var pulsePixel="//sst.dell.com/pc/dell/?";var pageEventValue=Marketing.UDO.pageevent?Marketing.UDO.pageevent:"pageview";if(Object.keys(Dell.Metrics.sc).length>0)datalayer=encodeURIComponent(JSON.stringify(Dell.Metrics.sc));var getCJStorageItem=sessionStorage.getItem("dellcjgdpr");var cjConsent=getCJStorageItem||dell_marketing_util.getParameterByName("cjgdpr",
location.href);if(!getCJStorageItem)sessionStorage.setItem("dellcjgdpr",cjConsent);Marketing.UDO.cjconsent=cjConsent=="1"?true:false;if(Object.keys(Marketing.UDO).length>0){Marketing.UDO.location=window.location.href;udolayer=encodeURIComponent(JSON.stringify(Marketing.UDO))}pulsePixel=pulsePixel+"dl\x3d"+datalayer+"\x26udo\x3d"+udolayer+"\x26space\x3dsst-"+Marketing.ensightenOptions.publishPath+"-loyalty"+"\x26pageevent\x3d"+pageEventValue;if(!window.__sst_ext_active)Marketing.imageRequest(pulsePixel)};
if(window.privacyReady){if(!window.privacyGPC){fire_pulse();window.addEventListener("udoReady",function(){fire_pulse()})}}else window.addEventListener("privacy-ready",function(){if(!window.privacyGPC){fire_pulse();window.addEventListener("udoReady",function(){fire_pulse()})}})}catch(e){dell_marketing.util.debug(e)}},3777482,[3815478],727254,[726737]);
Marketing.bindDependencyImmediate(function(){var Bootstrapper=window["Marketing"];var ensightenOptions=Marketing.ensightenOptions;try{Marketing.UDO.perfTimingStart("ruleId-"+this.id+"-deploymentId-"+this.deploymentId);Marketing.UDO.priorconsent=false;var fireMarketingServerComponent=function(orig_serverComponent,orig_args){if(!window.privacyGPC){Marketing.scDataObj.consent=true;Marketing.UDO.priorconsent=true;orig_serverComponent.apply(window[ensightenOptions.ns],orig_args)}};if(!Marketing.UDO.priorconsent){var orig_serverComponent=
window[ensightenOptions.ns].getServerComponent;window[ensightenOptions.ns].getServerComponent=function(){return function(){var orig_args=arguments;if(window.privacyReady)fireMarketingServerComponent(orig_serverComponent,orig_args);else window.addEventListener("privacy-ready",function(){fireMarketingServerComponent(orig_serverComponent,orig_args)})}}()}Marketing.UDO.perfTimingEnd("ruleId-"+this.id+"-deploymentId-"+this.deploymentId)}catch(e){dell_marketing_util.debug(e)}},3777480,[3815478],727252,
[726737]);Marketing.getServerComponent(Marketing.getExtraParams ? Marketing.getExtraParams() : undefined);}})();